PROGRAM GENERATE_SPINS_ONLY_FCC
  
  IMPLICIT NONE
  REAL(8), PARAMETER :: PI = 4.0D0 * ATAN(1.0D0), TWOPI = 2.0D0 * PI
  INTEGER, PARAMETER :: LSIZE = 4, TWOLSIZE = 2 * LSIZE
  !INTEGER, PARAMETER :: NUMPHASE = 5
  !TYPE(SPIN), DIMENSION(NUMPHASE,TWOLSIZE,TWOLSIZE,TWOLSIZE) :: SPINS
  INTEGER :: I,I1,I2,I3,J,t1,t2,t3,p1,p2,p3
  INTEGER, DIMENSION(3) :: ISC,IFCC,XFCC,XSC,QTHETA
  REAL(8) :: SPINS(3),THETA,RTHETA(3),COEFF
  REAL(8), DIMENSION(3) :: A1,A2,A3

  !FOR FACE CENTERED CUBIC
  A1 = DBLE([0,1,1])/2.0D0
  A2 = DBLE([1,0,1])/2.0D0
  A3 = DBLE([1,1,0])/2.0D0
  
  QTHETA = [0, LSIZE/2, LSIZE]
  !READ*,QTHETA
  COEFF = TWOPI/DBLE(TWOLSIZE)
  RTHETA = COEFF * DBLE(QTHETA)
  
  
  DO I1 = 1, TWOLSIZE
     ISC(1) = I1
     DO I2 = 1, TWOLSIZE
        ISC(2) = I2
        DO I3 = 1, TWOLSIZE
           ISC(3) = I3
           I = MOD(I1+I2+I3,2)
           IF (I == 0) CYCLE
           XFCC = ISC
           THETA = DOT_PRODUCT(DBLE(XFCC),RTHETA)
           SPINS(1) = SIN(THETA)
           SPINS(2) = 0.0D0
           SPINS(3) = COS(THETA)
           WRITE(3,'(3(I4,1X),3(F10.5,1X))')XFCC,SPINS
        END DO
     END DO
  END DO

END PROGRAM GENERATE_SPINS_ONLY_FCC
